# /home/sandeep/Projects/ScholarChat /migrations/versions/2530958ce438_add_embeddings_table.py
"""add embeddings table

Revision ID: 2530958ce438
Revises: 2e53d4ed9493
Create Date: 2026-05-11 23:30:22.789336

"""


from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector





# revision identifiers, used by Alembic.
revision: str = '2530958ce438'
down_revision: Union[str, Sequence[str], None] = '2e53d4ed9493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=True),   
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###
