"""add metadata fields to documents

Revision ID: 7893d952d0cd
Revises: 9fcba3cce526
Create Date: 2026-05-10 09:09:23.663787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7893d952d0cd'
down_revision: Union[str, Sequence[str], None] = '9fcba3cce526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('pages', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('title', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('author', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.alter_column('documents', 'upload_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'upload_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'author')
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'pages')
    # ### end Alembic commands ###
